//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Курсова_роботаEntities : DbContext
    {
        public Курсова_роботаEntities()
            : base("name=Курсова_роботаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cLine> cLine { get; set; }
        public virtual DbSet<cProductType> cProductType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vOrder> vOrder { get; set; }
        public virtual DbSet<vPlanLine> vPlanLine { get; set; }
        public virtual DbSet<vPlanLineCopy> vPlanLineCopy { get; set; }
        public virtual DbSet<cLineCopy> cLineCopy { get; set; }
        public virtual DbSet<cProductTypeCopy> cProductTypeCopy { get; set; }
        public virtual DbSet<vPlanLineCopy2> vPlanLineCopy2 { get; set; }
    }
}
