//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPlanLineCopy2
    {
        public int Id { get; set; }
        public Nullable<int> ReservedShipment { get; set; }
        public Nullable<int> ShipmentBuyersOrders { get; set; }
        public Nullable<int> Production { get; set; }
        public Nullable<int> EstimatedStockBalance { get; set; }
        public Nullable<int> AvailablePromise { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
    }
}
